version: '3'

volumes:
  vkapi:

services:

  mongo:
    image: mongo
    container_name: vkphotosmongo
    restart: unless-stopped
    tty: true
    volumes:
      - /opt/db/vkphotosmongo:/data/vkphoto
    networks:
      - vk_network

  flaskapi:
    build:
      context: .
      dockerfile: flaskapi/Dockerfile
    image: flaskapi
    command: flask run
    container_name: flaskvapi
    env_file:
      - .env
    restart: always
    tty: True
    working_dir: /flaskapi
    ports: 
        - "5000:5000"
    networks:
      - vk_network

  vkapi:
    build:
      context: .
      dockerfile: vkapi/Dockerfile
    image: vkapi
    container_name: vkphotos
    env_file:
      - .env
    restart: always
    tty: True
    working_dir: /vkapi
    volumes:
      - vkapi:/photos
    networks:
      - vk_network

networks:
  vk_network:
    driver: bridge
